### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by dicook** [srkobakian/review#1]
Due: mid September

- [x] Table added to the comparison section summarising the strengths/weaknesses of both **Steff**
- [x] Tilegram as one of the alternative displays **Steff**
- [x] Public atlases, reduce to 9(?). **Jessie**
    - Each one shown needs to be described and explained. 
    - Need links to find each of these
    - Explanation of lack of uncertainty
    - Resolution, state vs county
    - Legend and supporting explanations
    - Colour choices?
- [x] Maybe add small examples for the different supporting statistics **Steff**
- [x] Review intro and choropleth map sections **Di**
- [x] insert new figure that has 3 tiles of example supplementary graphs. 

- [x] Shift comparing mapping methods to end, possibly. Depends on what goes in animation
- [x] Micromaps work by Dan Carr and BLS **Steff**
- [x] Paragraph structure, first paragraph of interactive section needs to set up the section **Steff**
- [x] Animation could point to a couple of public atlases that allow animation and explain how it is used **Steff**
- [x] Add some figures for the animation vs interactivity **Steff**

**Comment by jesse-jesse** [comment]
Updated the grid of cancer maps to 9 tiles. Still need to annotate the tiles and add links to original pages.  tiles were selected to show : different resolution (global, national, state), examples of low count areas, divergent vs continuous scales, rates vs relative risk. Hopefully tomorrow I can get time to put descriptions for each before I head off on Saturday.

Didn't select specifically for colour choices, but there is enough variation in the tiles to discuss this. 

I'm not sure if uncertainty should be covered here, I think it will be better in a few other additional graphs.

**Comment by jesse-jesse** [comment]
Added links to the fig caption, but thinking that an extra table that lists, the cancer type, the measure, the year. might be handy. Maybe in the the appendix. The figure caption is already too big I don't want to add any more detail to it. 

Also - need to add an in text description of the variation shown in these graphs. ie the measures, the resolutions, highlighting low count areas, different colour choices, and different legend approaches.

**Comment by srkobakian** [comment]
I have been trying to implement tilegrams or rectangular cartograms in R, managed to get a tilegram, the rectangular cartograms are more complicated

**Comment by srkobakian** [comment]
@jesse-jesse I have found a way to implement the grid for the choropleth and interactivity controls which also allows us to letter them in R.
I have checked the links are correct but I would appreciate if you could double check as I did some rearranging
