### ISSUE TITLE
Atlas vs maps

### ISSUE THREAD

**Issue by jesse-jesse** [srkobakian/review#2]
Is there an important difference between a cancer atlas and a cancer map? We use both in the review article. I'm wondering which one to use?

**Comment by srkobakian** [comment]
Simply:
a cancer map displays geographic occurrence and variation of a single phenomenon, one single map.
A cancer atlas is a collection of maps, used for comparisons, it may be different cancer types, or sex, or risk factors

"To the best of our knowledge, the first cancer atlas was Haviland’s maps of cancers in women in England and Wales, published in 1875"
d’Onofrio, Alberto, Chiara Mazzetta, Chris Robertson, Michel Smans, Peter Boyle, and Mathieu
Boniol. 2016. “Maps and Atlases of Cancer Mortality: A Review of a Useful Tool to Trigger New
Questions.” Journal Article. Ecancermedicalscience 10: 670–70. https://doi.org/10.3332/ecancer.
2016.670.
